### ISSUE TITLE
在create_scenario.py，点开dreamview后自车不朝着终点运动

### ISSUE THREAD

**Issue by lsm2842035890** [Software-Aurora-Lab/scenoRITA-7.0#4]
![A${IW7 ~_KDT1TST(U%H{@V](https://github.com/user-attachments/assets/577e52c2-c35d-4594-bbbd-5c00772926d6)
点开dreamview之后，我在最上面选择完地图和车辆型号，就固定在起点不动了~

**Comment by YuqiHuai** [comment]
你现在跑一下create scenario看看 跑之后不应该点dreamview的

**Comment by lsm2842035890** [comment]
跑完了，直接打印了done就结束了~

**Comment by lsm2842035890** [comment]
咱们能加个微信吗，交流方便一点~我加您

**Comment by YuqiHuai** [comment]
Hmm那有点奇怪 这会儿有点晚了我明天白天看看哪里可能有问题

**Comment by YuqiHuai** [comment]
我这边还是暂时不加微信 工作相关的我会留在邮箱里未读这样之后还能记得回复 微信的话基本不回复 希望理解

**Comment by lsm2842035890** [comment]
dreamview.INFO
I0913 18:32:51.055742   128 simulation_world_service.h:240] Has not received any data from /apollo/sensor/gnss/odometry
I0913 18:32:51.055757   128 simulation_world_service.h:240] Has not received any data from /apollo/audio_detection
I0913 18:32:51.055759   128 simulation_world_service.h:240] Has not received any data from /apollo/storytelling
I0913 18:32:51.055761   128 simulation_world_service.h:240] Has not received any data from /apollo/perception/obstacles
I0913 18:32:51.055773   128 simulation_world_service.h:240] Has not received any data from /apollo/control
I0913 18:33:01.055750   128 simulation_world_service.h:240] Has not received any data from /apollo/sensor/gnss/odometry
I0913 18:33:01.055769   128 simulation_world_service.h:240] Has not received any data from /apollo/audio_detection
I0913 18:33:01.055773   128 simulation_world_service.h:240] Has not received any data from /apollo/storytelling
I0913 18:33:01.055775   128 simulation_world_service.h:240] Has not received any data from /apollo/perception/obstacles
I0913 18:33:01.055791   128 simulation_world_service.h:240] Has not received any data from /apollo/control

mainboard.INFO
Log file created at: 2024/09/13 18:30:14
Running on machine: in-dev-docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W0913 18:30:14.020870  4624 scheduler_factory.cc:63] Scheduler conf named /apollo/cyber/conf/planning.conf not found, use default.
I0913 18:30:14.020964  4627 processor.cc:42] processor_tid: 4627
I0913 18:30:14.020993  4628 processor.cc:42] processor_tid: 4628
I0913 18:30:14.021015  4629 processor.cc:42] processor_tid: 4629
I0913 18:30:14.021037  4630 processor.cc:42] processor_tid: 4630
I0913 18:30:14.021054  4631 processor.cc:42] processor_tid: 4631
I0913 18:30:14.021085  4632 processor.cc:42] processor_tid: 4632
I0913 18:30:14.021106  4633 processor.cc:42] processor_tid: 4633
I0913 18:30:14.021157  4635 processor.cc:42] processor_tid: 4635
I0913 18:30:14.021158  4634 processor.cc:42] processor_tid: 4634
I0913 18:30:14.021176  4636 processor.cc:42] processor_tid: 4636
I0913 18:30:14.021196  4637 processor.cc:42] processor_tid: 4637
I0913 18:30:14.021216  4638 processor.cc:42] processor_tid: 4638
I0913 18:30:14.021238  4639 processor.cc:42] processor_tid: 4639
I0913 18:30:14.021255  4640 processor.cc:42] processor_tid: 4640
I0913 18:30:14.021278  4641 processor.cc:42] processor_tid: 4641
I0913 18:30:14.021291  4642 processor.cc:42] processor_tid: 4642
I0913 18:30:14.021292  4624 init.cc:113] Register exit handle succ.
I0913 18:30:14.021579  4624 module_controller.cc:65] Start initialize dag: /apollo/modules/planning/dag/planning.dag
I0913 18:30:14.021620  4624 class_loader.cc:37] Begin LoadLibrary: /apollo/bazel-bin/modules/planning/libplanning_component.so
I0913 18:30:14.661528  4624 scheduler.cc:55] create croutine: /internal/task0
I0913 18:30:14.661561  4624 scheduler.cc:55] create croutine: /internal/task1
I0913 18:30:14.661567  4624 scheduler.cc:55] create croutine: /internal/task2
I0913 18:30:14.661581  4624 scheduler.cc:55] create croutine: /internal/task3
I0913 18:30:14.661599  4624 scheduler.cc:55] create croutine: /internal/task4
I0913 18:30:14.661607  4624 scheduler.cc:55] create croutine: /internal/task5
I0913 18:30:14.661613  4624 scheduler.cc:55] create croutine: /internal/task6
I0913 18:30:14.661628  4624 scheduler.cc:55] create croutine: /internal/task7
I0913 18:30:14.661636  4624 scheduler.cc:55] create croutine: /internal/task8
I0913 18:30:14.661648  4624 scheduler.cc:55] create croutine: /internal/task9
I0913 18:30:14.661655  4624 scheduler.cc:55] create croutine: /internal/task10
I0913 18:30:14.661661  4624 scheduler.cc:55] create croutine: /internal/task11
I0913 18:30:14.661666  4624 scheduler.cc:55] create croutine: /internal/task12
I0913 18:30:14.661671  4624 scheduler.cc:55] create croutine: /internal/task13
I0913 18:30:14.661679  4624 scheduler.cc:55] create croutine: /internal/task14
I0913 18:30:14.661682  4624 scheduler.cc:55] create croutine: /internal/task15
I0913 18:30:14.664407  4624 scheduler.cc:55] create croutine: planning_/apollo/routing_response
I0913 18:30:14.665004  4624 scheduler.cc:55] create croutine: planning_/apollo/perception/traffic_light
I0913 18:30:14.665280  4624 scheduler.cc:55] create croutine: planning_/apollo/planning/pad
I0913 18:30:14.665603  4624 scheduler.cc:55] create croutine: planning_/apollo/storytelling
I0913 18:30:14.693951  4624 scheduler.cc:55] create croutine: planning_/apollo/canbus/chassis
I0913 18:30:14.694319  4624 scheduler.cc:55] create croutine: planning_/apollo/localization/pose
I0913 18:30:14.695271  4624 scheduler.cc:55] create croutine: planning_/apollo/prediction
I0913 18:30:14.695539  4624 scheduler.cc:55] create croutine: planning

map.INFO
Log file created at: 2024/09/13 18:30:14
Running on machine: in-dev-docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0913 18:30:14.658444  4624 hdmap.cc:24] Loading HDMap: /apollo/modules/map/data/borregas_ave/base_map.bin ...
I0913 18:30:14.661090  4624 hdmap_util.cc:78] Load HDMap success: /apollo/modules/map/data/borregas_ave/base_map.bin

planning.INFO
E0913 18:30:46.201956  4633 pnc_map.cc:269] Route is empty.
E0913 18:30:46.202033  4633 planning_component.cc:246] routing not ready; skip the planning cycle.
E0913 18:30:46.202101  4633 planning_component.cc:157] Input check failed
E0913 18:30:46.301887  4628 reference_line_provider.cc:205] Routing is not ready.
E0913 18:30:46.301986  4639 pnc_map.cc:269] Route is empty.
E0913 18:30:46.302052  4639 planning_component.cc:246] routing not ready; skip the planning cycle.
E0913 18:30:46.302098  4639 planning_component.cc:157] Input check failed
E0913 18:30:46.401986  4627 reference_line_provider.cc:205] Routing is not ready.
E0913 18:30:46.402143  4635 pnc_map.cc:269] Route is empty.
E0913 18:30:46.402220  4635 planning_component.cc:246] routing not ready; skip the planning cycle.
E0913 18:30:46.402287  4635 planning_component.cc:157] Input check failed
E0913 18:30:46.501965  4629 reference_line_provider.cc:205] Routing is not ready.
E0913 18:30:46.502075  4640 pnc_map.cc:269] Route is empty.
E0913 18:30:46.502153  4640 planning_component.cc:246] routing not ready; skip the planning cycle.
E0913 18:30:46.502220  4640 planning_component.cc:157] Input check failed


predict.INFO
Log file created at: 2024/09/13 18:30:11
Running on machine: in-dev-docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0913 18:30:11.817034  4526 class_loader_utility.h:79] registerclass:PredictorSubmodule,apollo::cyber::ComponentBase,/apollo/bazel-bin/modules/prediction/libprediction_component.so
I0913 18:30:11.817097  4526 class_loader_utility.h:79] registerclass:EvaluatorSubmodule,apollo::cyber::ComponentBase,/apollo/bazel-bin/modules/prediction/libprediction_component.so
I0913 18:30:11.817111  4526 class_loader_utility.h:79] registerclass:PredictionComponent,apollo::cyber::ComponentBase,/apollo/bazel-bin/modules/prediction/libprediction_component.so
I0913 18:30:11.820133  4526 predictor_manager.cc:334] Predictor [0] is registered.
I0913 18:30:11.820143  4526 predictor_manager.cc:334] Predictor [3] is registered.
I0913 18:30:11.820145  4526 predictor_manager.cc:334] Predictor [5] is registered.
I0913 18:30:11.820148  4526 predictor_manager.cc:334] Predictor [1] is registered.
I0913 18:30:11.820151  4526 predictor_manager.cc:334] Predictor [4] is registered.
I0913 18:30:11.820153  4526 predictor_manager.cc:334] Predictor [6] is registered.
I0913 18:30:11.820155  4526 predictor_manager.cc:334] Predictor [7] is registered.
I0913 18:30:11.820165  4526 predictor_manager.cc:334] Predictor [8] is registered.
I0913 18:30:11.821635  4526 container_manager.cc:63] Container [11] is registered.
I0913 18:30:11.821642  4526 container_manager.cc:63] Container [5] is registered.
I0913 18:30:11.821650  4526 container_manager.cc:63] Container [6] is registered.
I0913 18:30:11.821652  4526 container_manager.cc:63] Container [40] is registered.
I0913 18:30:11.821655  4526 container_manager.cc:63] Container [75] is registered.
I0913 18:30:11.824812  4526 mlp_evaluator.cc:365] Succeeded in loading the model file: /apollo/modules/prediction/data/mlp_vehicle_model.bin.
I0913 18:30:11.824826  4526 evaluator_manager.cc:461] Evaluator [0] is registered.
I0913 18:30:11.824829  4526 evaluator_manager.cc:461] Evaluator [2] is registered.
I0913 18:30:12.446278  4526 evaluator_manager.cc:461] Evaluator [3] is registered.
I0913 18:30:12.447073  4526 evaluator_manager.cc:461] Evaluator [4] is registered.
I0913 18:30:12.447080  4526 evaluator_manager.cc:461] Evaluator [5] is registered.
I0913 18:30:12.452931  4526 evaluator_manager.cc:461] Evaluator [6] is registered.
I0913 18:30:12.456216  4526 evaluator_manager.cc:461] Evaluator [9] is registered.
I0913 18:30:12.529857  4526 evaluator_manager.cc:461] Evaluator [8] is registered.
I0913 18:30:13.548676  4526 evaluator_manager.cc:461] Evaluator [10] is registered.
I0913 18:30:13.980026  4526 evaluator_manager.cc:461] Evaluator [11] is registered.
I0913 18:30:13.985278  4526 vectornet_evaluator.cc:458] CUDA is available
I0913 18:30:14.657678  4526 evaluator_manager.cc:461] Evaluator [12] is registered.
I0913 18:30:14.657742  4526 evaluator_manager.cc:185] Defined vehicle on lane obstacle evaluator [3]
I0913 18:30:14.657744  4526 evaluator_manager.cc:187] Defined cyclist on lane obstacle evaluator [5]
I0913 18:30:14.657745  4526 evaluator_manager.cc:189] Defined default on lane obstacle evaluator [0]
I0913 18:30:14.657752  4526 predictor_manager.cc:108] Defined vehicle on lane obstacle predictor [3].
I0913 18:30:14.657752  4526 predictor_manager.cc:110] Defined vehicle off lane obstacle predictor [1].
I0913 18:30:14.657753  4526 predictor_manager.cc:112] Defined bicycle on lane obstacle predictor [0].
I0913 18:30:14.657755  4526 predictor_manager.cc:114] Defined bicycle off lane obstacle predictor [1].
I0913 18:30:14.657756  4526 predictor_manager.cc:116] Defined pedestrian obstacle predictor [1].
I0913 18:30:14.657757  4526 predictor_manager.cc:118] Defined default on lane obstacle predictor [0].
I0913 18:30:14.657759  4526 predictor_manager.cc:120] Defined default off lane obstacle predictor [1].


routing.INFO
Log file created at: 2024/09/13 18:30:08
Running on machine: in-dev-docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0913 18:30:08.835546  4438 class_loader_utility.h:79] registerclass:RoutingComponent,apollo::cyber::ComponentBase,/apollo/bazel-bin/modules/routing/librouting_component.so
I0913 18:30:08.839085  4438 routing_component.cc:35] Config file: /apollo/modules/routing/conf/routing_config.pb.txt is loaded.
I0913 18:30:08.840986  4438 routing.cc:39] Use routing topology graph path: /apollo/modules/map/data/borregas_ave/routing_map.bin
I0913 18:30:08.841549  4438 topo_graph.cc:83] Load Topo data successful.
I0913 18:30:08.841553  4438 navigator.cc:111] The navigator is ready.
I0913 18:30:08.844307  4438 routing.cc:54] Routing service is ready.

**Comment by lsm2842035890** [comment]
解决了~是因为我用pycharm打开的项目，apollo里面的文件导入其他文件的包路径不正确，之前我也是遇到这种情况，换到vscode里打开项目就ok了，在vscode和pycharm的导入其他py文件里的函数from ____ import _____ from后面写的是不一样的

**Comment by YuqiHuai** [comment]
才看到消息，我这边确实用的不是PyCharm，没想到这个也会有问题。那我先关闭这个Issue，如果有其他问题重新打开。
