### ISSUE TITLE
关于dreamview能加载的地图

### ISSUE THREAD

**Issue by lsm2842035890** [Software-Aurora-Lab/scenoRITA-7.0#5]
hi，YuqiHuai,中秋快乐~
用create_scenario.py这个文件加载除了borregas_ave的地图，打开dreamview是不显示道路拓扑的，dreamview的选项框里只有borregas_ave，是因为编译apollo的时候，没加入其他几个地图吗（这个我不太懂~），或许在哪个文件里可以把其他几个地图也选择进去，重新编译一下dreamview就能选择更多的地图了？
![{O5~C }V__S@VB(QSJBW4G8](https://github.com/user-attachments/assets/7e6c7c6a-7ed1-4024-9efe-054df08e7a3c)
![%PARMR@QP%S~FQ97G S3X6N](https://github.com/user-attachments/assets/bd4d466b-7397-40cb-9653-d77027d2b82d)
![image](https://github.com/user-attachments/assets/2e95296c-75d2-43df-9ec1-47f90fb7de5a)

**Comment by YuqiHuai** [comment]
Hi 抱歉 正好过节赶上出去了 不过这个问题比较简单 需要在Apollo里这里添加地图 https://github.com/ApolloAuto/apollo/tree/r7.0.0/modules/map/data

scenoRITA里我可能把Apollo本身mount地图的Docker script去掉了，所以需要手动创建文件夹，把HD Map(base_map.bin)放进去，然后按Apollo的说明生成其他文件。

**Comment by lsm2842035890** [comment]
https://github.com/ApolloAuto/apollo/tree/r7.0.0/modules/map/data这个教程我能懂，生成好的三个bin文件放到指定位置，然后改写global_flagfile.txt，做完这些比如我该用什么命令执行，去让我加入的地图在dreamview上显示出来，后面的步骤我不太会，看了很多博客跟这个链接差不多是一样的后面的步骤就没有了。
“scenoRITA里我可能把Apollo本身mount地图的Docker script去掉了”，指的是这个地方吗
![4ZF7FP$} %Y}W$ CU5}%4D1](https://github.com/user-attachments/assets/6012a208-8c58-4e56-a0d2-f016978b430d)

其他几个地图（san_mateo,san_fra,sunnyvale）都在apollo/modules/map/data里存着，并且global_flagfile.txt也都有他们的路径，只要是把本身mount地图的Docker script加回来，我就可以在dreamview的map里选择到另外几个地图了吗

**Comment by YuqiHuai** [comment]
- 地图文件生成后需要重启Dreamview然后就能显示了
- 我指的是 https://github.com/Software-Aurora-Lab/scenoRITA-7.0/blob/fe24d3426aaa47d533dfcb76a04ad946a7c6cbfc/data/scripts/dev_start.sh#L415
- san_francisco不一定在，因为那个是LGSVL里下载过来的，其他的应该在。

**Comment by YuqiHuai** [comment]
@lsm2842035890 回来干活了，您这边加载其他地图跑起来了吗？

**Comment by lsm2842035890** [comment]
shalun,sanmeteo,san frans,sunnyvaleloop,这几个地图可以在dreamview里使用了，刚刚又试了一下carla_town01这个地图，第一次试能在dreamview里加载地图了，后面再试连地图都不加载了，似乎是routing有问题，
![$CRBLLH93EKV~A6_QAH1JKQ](https://github.com/user-attachments/assets/c45a7ddd-48c7-4899-9458-86ea45e68d2c)

1. 这是main.info

Log file created at: 2024/09/19 09:20:57
Running on machine: in-dev-docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0919 09:20:57.549633  5769 global_data.cc:153] host ip: 172.17.0.2
W0919 09:20:57.549662  5769 environment.h:33] Environment variable [CYBER_PATH] not set, fallback to 
W0919 09:20:57.550446  5769 environment.h:33] Environment variable [CYBER_PATH] not set, fallback to 
W0919 09:20:57.550455  5769 scheduler_factory.cc:63] Scheduler conf named /apollo/cyber/conf/main_5769.conf not found, use default.
W0919 09:20:57.550462  5769 environment.h:33] Environment variable [CYBER_PATH] not set, fallback to 
I0919 09:20:57.550540  5776 processor.cc:42] processor_tid: 5776
I0919 09:20:57.550575  5777 processor.cc:42] processor_tid: 5777
I0919 09:20:57.550601  5778 processor.cc:42] processor_tid: 5778
I0919 09:20:57.550626  5779 processor.cc:42] processor_tid: 5779
I0919 09:20:57.550648  5780 processor.cc:42] processor_tid: 5780
I0919 09:20:57.550674  5781 processor.cc:42] processor_tid: 5781
I0919 09:20:57.550698  5782 processor.cc:42] processor_tid: 5782
I0919 09:20:57.550733  5783 processor.cc:42] processor_tid: 5783
I0919 09:20:57.550755  5785 processor.cc:42] processor_tid: 5785
I0919 09:20:57.550755  5784 processor.cc:42] processor_tid: 5784
I0919 09:20:57.550774  5786 processor.cc:42] processor_tid: 5786
I0919 09:20:57.550798  5787 processor.cc:42] processor_tid: 5787
I0919 09:20:57.550825  5788 processor.cc:42] processor_tid: 5788
I0919 09:20:57.550844  5789 processor.cc:42] processor_tid: 5789
I0919 09:20:57.550871  5790 processor.cc:42] processor_tid: 5790
W0919 09:20:57.550880  5769 environment.h:33] Environment variable [sysmo_start] not set, fallback to 
I0919 09:20:57.550884  5769 init.cc:113] Register exit handle succ.
I0919 09:20:57.550889  5791 processor.cc:42] processor_tid: 5791
I0919 09:20:57.550978  5769 map_service.cc:107] Failed to open map meta file: /metaInfo.json
I0919 09:20:57.550980  5769 map_service.cc:144] Updated with map: x_offset 0, y_offset 0
I0919 09:20:57.553745  5769 scheduler.cc:55] create croutine: sim_control_standalone_/apollo/localization/pose
I0919 09:20:57.561864  5769 scheduler.cc:55] create croutine: sim_control_standalone_/apollo/planning
I0919 09:20:57.562481  5769 scheduler.cc:55] create croutine: sim_control_standalone_/apollo/routing_response
I0919 09:20:57.563383  5769 scheduler.cc:55] create croutine: sim_control_standalone_/apollo/navigation
I0919 09:20:57.565173  5769 scheduler.cc:55] create croutine: sim_control_standalone_/apollo/prediction
I0919 09:20:57.570879  5769 timer.cc:137] start timer [0]
I0919 09:20:57.570888  5769 timer.cc:137] start timer [1]
I0919 09:20:57.670989  5805 scheduler.cc:55] create croutine: /internal/task0
I0919 09:20:57.671031  5805 scheduler.cc:55] create croutine: /internal/task1
I0919 09:20:57.671048  5805 scheduler.cc:55] create croutine: /internal/task2
I0919 09:20:57.671066  5805 scheduler.cc:55] create croutine: /internal/task3
I0919 09:20:57.671079  5805 scheduler.cc:55] create croutine: /internal/task4
I0919 09:20:57.671090  5805 scheduler.cc:55] create croutine: /internal/task5
I0919 09:20:57.671103  5805 scheduler.cc:55] create croutine: /internal/task6
I0919 09:20:57.671113  5805 scheduler.cc:55] create croutine: /internal/task7
I0919 09:20:57.671125  5805 scheduler.cc:55] create croutine: /internal/task8
I0919 09:20:57.671135  5805 scheduler.cc:55] create croutine: /internal/task9
I0919 09:20:57.671146  5805 scheduler.cc:55] create croutine: /internal/task10
I0919 09:20:57.671156  5805 scheduler.cc:55] create croutine: /internal/task11
I0919 09:20:57.671173  5805 scheduler.cc:55] create croutine: /internal/task12
I0919 09:20:57.671185  5805 scheduler.cc:55] create croutine: /internal/task13
I0919 09:20:57.671195  5805 scheduler.cc:55] create croutine: /internal/task14
I0919 09:20:57.671206  5805 scheduler.cc:55] create croutine: /internal/task15
W0919 09:21:03.573150  5805 rate.cc:96] Detect forward jumps in time

2. cyber_recorder.info

Log file created at: 2024/09/19 09:21:05
Running on machine: in-dev-docker
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0919 09:21:05.445225  6119 global_data.cc:153] host ip: 172.17.0.2
W0919 09:21:05.445259  6119 environment.h:33] Environment variable [CYBER_PATH] not set, fallback to 
W0919 09:21:05.446465  6119 environment.h:33] Environment variable [CYBER_PATH] not set, fallback to 
W0919 09:21:05.446478  6119 scheduler_factory.cc:63] Scheduler conf named /apollo/cyber/conf/cyber_recorder_6119.conf not found, use default.
W0919 09:21:05.446485  6119 environment.h:33] Environment variable [CYBER_PATH] not set, fallback to 
I0919 09:21:05.446556  6126 processor.cc:42] processor_tid: 6126
I0919 09:21:05.446576  6127 processor.cc:42] processor_tid: 6127
I0919 09:21:05.446602  6128 processor.cc:42] processor_tid: 6128
I0919 09:21:05.446628  6129 processor.cc:42] processor_tid: 6129
I0919 09:21:05.446648  6130 processor.cc:42] processor_tid: 6130
I0919 09:21:05.446671  6131 processor.cc:42] processor_tid: 6131
I0919 09:21:05.446691  6132 processor.cc:42] processor_tid: 6132
I0919 09:21:05.446728  6133 processor.cc:42] processor_tid: 6133
I0919 09:21:05.446760  6134 processor.cc:42] processor_tid: 6134
I0919 09:21:05.446760  6135 processor.cc:42] processor_tid: 6135
I0919 09:21:05.446795  6136 processor.cc:42] processor_tid: 6136
I0919 09:21:05.446818  6137 processor.cc:42] processor_tid: 6137
I0919 09:21:05.446846  6138 processor.cc:42] processor_tid: 6138
I0919 09:21:05.446863  6139 processor.cc:42] processor_tid: 6139
I0919 09:21:05.446883  6140 processor.cc:42] processor_tid: 6140
W0919 09:21:05.446893  6119 environment.h:33] Environment variable [sysmo_start] not set, fallback to 
I0919 09:21:05.446897  6119 init.cc:113] Register exit handle succ.
I0919 09:21:05.446904  6141 processor.cc:42] processor_tid: 6141
I0919 09:21:05.452013  6149 play_task_producer.cc:235] preload_size: 33
3.map.info没有文件输出

**Comment by lsm2842035890** [comment]
> @lsm2842035890 回来干活了，您这边加载其他地图跑起来了吗？

![}0QDDA1B3{_BIES~`TOT5 J](https://github.com/user-attachments/assets/eda02878-daeb-46b3-900e-e779ed3f22ea)
routing_map.bin,sim_map.bin我拿的是carla_apollo_bridge里现成的，可能是它本身的三个bin文件的问题吗~

**Comment by YuqiHuai** [comment]
应该不是，看截图就只是没有初始化车辆位置而已。点开SimControl试试。

**Comment by lsm2842035890** [comment]
![image](https://github.com/user-attachments/assets/2c343669-2317-4333-a66d-9128d2459fa9)
这个地方吗，点不了，打不开simcontrol~

**Comment by YuqiHuai** [comment]
@lsm2842035890 您吧base_map.bin压缩了上传到这里我看看

**Comment by lsm2842035890** [comment]
[carla_town01.zip](https://github.com/user-attachments/files/17108903/carla_town01.zip)

**Comment by YuqiHuai** [comment]
@lsm2842035890 这个地图文件可能有点问题 我不太确定问题出在哪 但是应该是Dreamview的display issue。
先把地图设置为Carla Town1，然后打开SimControl，确认Localization Module有消息（通过cyber_monitor或者Dreamview Module Delay）。然后把地图设置为Apollo自带的地图（比如Borregas），刷新界面，这时屏幕中间车应该会出来。然后再把地图改回Carla。

－－－

改地图会影响ADS modules比如Planning/Routing但是对Dreamview和SimControl没啥影响，所以这样操作之后routing request也是可以发送并可视化的。

![image](https://github.com/user-attachments/assets/5716b4e1-2093-4ca2-8593-2d29f4d62612)

**Comment by lsm2842035890** [comment]
好的好的感谢，我试一下！

**Comment by lsm2842035890** [comment]
把hdmap信号灯全部去掉，是在basemap.txt里把trafficlight有关的全部删掉，然后用apollo/modules/tools/create_map里面的工具把basemap.txt转换成basemap.bin,再用./scripts/generate_routing_topo_graph.sh 和bazel-bin/modules/map/tools/sim_map_generator转换成sim_map.bin和routing_map.bin，是这个流程嘛~

**Comment by YuqiHuai** [comment]
Generate的那部分是的 不过修改hdmap我是直接修改protobuf object。Apollo的base map bin其实就是个二进制的protobuf。
