### ISSUE TITLE
obstacle的生成

### ISSUE THREAD

**Issue by lsm2842035890** [Software-Aurora-Lab/scenoRITA-7.0#6]
[https://github.com/Software-Aurora-Lab/scenoRITA-7.0/blob/main/src/scenoRITA/components/scenario_generator.py](url)
hi，关于scenario_generator.py里的generate_perception_obstacle函数，我看了一下代码逻辑，obstacles的轨迹是根据route提前计算好每一步的位置然后写入文件，而ego_car只根据生成起点和终点信息,中间过程走哪里怎么走是运行时实时计算的，我理解的对嘛~

**Comment by YuqiHuai** [comment]
对，obstacle每一步怎么走都是由Approach计算，类似于其他approach中模拟器（SVL）负责计算障碍物的轨迹。我们只告诉Apollo从哪开始，要去哪，具体怎么去由Apollo的Routing+Planning计算。
